name: Zip and Push to Artifactory

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Release Please
        id: release
        uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      - name: Zip the repository with version
        run: |
          echo ${{ steps.release.outputs }}
          VERSION=$(echo "${{ steps.release.outputs.release_created }}" | jq -r .tagName)
          zip -r my_function_$VERSION.zip . -x ".git/*" ".github/*"

      - name: Push to Artifactory
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          VERSION=$(echo "${{ steps.release.outputs.release_created }}" | jq -r .tagName)
          echo "$ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -X PUT "$ARTIFACTORY_URL/my-repo/my_function_$VERSION.zip" -T my_function_$VERSION.zi"p
